# permissions for end users to edit listings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listing-editor-role
rules:
- apiGroups:
  - webapp.begin
  resources:
  - listings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.begin
  resources:
  - listings/status
  verbs:
  - get
