# permissions for end users to view listpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listpod-viewer-role
rules:
- apiGroups:
  - webapp.begin
  resources:
  - listpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.begin
  resources:
  - listpods/status
  verbs:
  - get
