# permissions for end users to edit listpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: listpod-editor-role
rules:
- apiGroups:
  - webapp.begin
  resources:
  - listpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.begin
  resources:
  - listpods/status
  verbs:
  - get
