---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-timer
spec:
  replicas: 1
  selector:
    matchLabels:
      lbl: myTime
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        lbl: myTime
    spec:
      containers:
        - image:  ups91/kube-test-pods:timer
          imagePullPolicy: Always
          name: timer
          ports:
            - containerPort: 8002
          resources:
            limits:
              cpu: "100m"
              memory: "32Mi"
