---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ ".Values.ingress-nginx.ext-host-name" }}
      http:
        paths:
          - backend:
              serviceName: service-colorer
              servicePort: 8003
            path: /job(/|$)(.*)
          - backend:
              serviceName: service-timer
              servicePort: 8002
            path: /time([r]/|$)(.*)
          - backend:
              serviceName: service-echo
              servicePort: 8001
            path: /var(/|$)(.*)
