---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: {{ .Values.namespace.name }}
  labels:
    control-plane: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Values.namespace.name }}
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: {{ .Values.namespace.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName.name }}
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: ups91/kube-test-pods:listpod
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
